### ISSUE TITLE
Doesn't work when keyboard is opened from a UITextView

### ISSUE THREAD

**Issue by mennopruijssers** [danielamitay/DAKeyboardControl#4]
When the keyboard is opened from a UITextView instead of a UITextField, it doesn't work.
activeInput.inputAccessoryView.superview is nil, so the activeKeyboard-ivar isn't set.

**Comment by jerrin15** [comment]
Is this working for everyone now? I have a UITextView , which when called brings up my input accessory view but its position is not on top of the keyboard. When i drag the auto-translate bar on the keyboard it gets set correctly.

**Comment by jerrin15** [comment]
Is this working for everyone now? I have a UITextView , which when called brings up my custom input accessory view but its position is not on top of the keyboard. When i drag the auto-translate bar on the keyboard it gets set correctly.So every time on the initial call the input accessory view is placed on top of the keyboard, on interaction with the keyboard it gets set correctly.

I currently used the following code snippets only
 
    self.view.keyboardTriggerOffset = keyboardView.bounds.size.height;
    
    [self.view addKeyboardPanningWithFrameBasedActionHandler:^(CGRect keyboardFrameInView, BOOL opening, BOOL closing) {
        CGRect toolBarFrame = keyboardView.frame;
        toolBarFrame.origin.y = keyboardFrameInView.origin.y - toolBarFrame.size.height;
        keyboardView.frame = toolBarFrame;
        
    } constraintBasedActionHandler:nil];

I also call the 
    [textView setInputAccessoryView:keyboardView];

in the UITextView shouldbegin method
