### ISSUE TITLE
Not working right in iOS9 (Xcode7)

### ISSUE THREAD

**Issue by rcmstark** [danielamitay/DAKeyboardControl#97]
Hi, your control is pretty good and work great in iOS8. But now, i just tested in iOS9 and it's not the some.

Can you update the code to make it work in iOS9?

**Comment by rmprosser** [comment]
Duplicate of issue #95 (and "not the same" isn't very specific)

**Comment by rcmstark** [comment]
Yeah, it's a duplicate. My bad, closing now.
